FROM zabbix/zabbix-web-apache-mysql:alpine-6.0-latest

# Replace Zabbix logos with your custom ones
COPY ./custom/logo.svg /usr/share/zabbix/assets/img/logo.svg
COPY ./custom/logo_login.svg /usr/share/zabbix/assets/img/logo_login.svg
